window.menuItems = [
  { category: "Chef Special Menu", name: "Pickled Mustard Greens & Shredded Pork Noodle Soup", image: "新菜品图/Chef special menu/雪菜肉丝面.png", price: "$17.50" },
  { category: "Chef Special Menu", name: "Shredded Pork & Green Pepper Rice Bowl", image: "新菜品图/Chef special menu/青椒肉丝面.png", price: "$17.80" },
  { category: "Chef Special Menu", name: "Yu Xiang Shredded Pork Rice Bowl", image: "新菜品图/Chef special menu/鱼香肉丝面.png", price: "$17.80" },
  { category: "Chef Special Menu", name: "House Special Mala Ramen", image: "新菜品图/Chef special menu/特色麻辣拉面.png", price: "$26.80" },
  { category: "Sizzling", name: "Shogayaki Beef Sizzling", image: "新菜品图/Sizzling/Shogayaki Beef Sizzling.png", price: "$17.50" },
  { category: "Sizzling", name: "Black Pepper Beef Sizzling", image: "新菜品图/Sizzling/Black Pepper Beef Sizzling.png?v=rice-topping-1", price: "$17.50" },
  { category: "Sizzling", name: "Yakiniku Beef Sizzling", image: "新菜品图/Sizzling/Yakiniku Beef Sizzling.png", price: "$17.50" },
  { category: "Ramen", name: "Karaage Chicken Ramen", image: "新菜品图/汤面/Ramen/N5 Karaage Chicken Ramen remade.png", price: "$17.50" },
  { category: "Ramen", name: "Teriyaki Chicken Ramen", image: "新菜品图/汤面/Ramen/N6 Teriyaki Chicken Ramen remade.png", price: "$17.50" },
  { category: "Ramen", name: "Shogayaki Beef Ramen", image: "新菜品图/汤面/Ramen/N9 Shogayaki Beef Ramen remade.png", price: "$17.50" },
  { category: "Ramen", name: "Chicken Katsu Ramen", image: "新菜品图/汤面/Ramen/N7 Chicken Katsu Ramen remade.png", price: "$17.50" },
  { category: "Ramen", name: "Roasted Pork Ramen", image: "新菜品图/汤面/Ramen/N8 Roasted Pork Ramen remade.png", price: "$17.50" },
  { category: "Udon", name: "Karaage Chicken Udon", image: "新菜品图/汤面/Udon/N1 Karaage Chicken Udon remade.png", price: "$16.50" },
  { category: "Udon", name: "Teriyaki Chicken Udon", image: "新菜品图/汤面/Udon/N2 Teriyaki Chicken Udon remade.png", price: "$16.50" },
  { category: "Udon", name: "Shogayaki Beef Udon", image: "新菜品图/汤面/Udon/N3 Shogayaki Beef Udon remade.png", price: "$16.50" },
  { category: "Udon", name: "Chicken Katsu Udon", image: "新菜品图/汤面/Udon/N3 Chicken Katsu Udon remade.png", price: "$16.50" },
  { category: "Udon", name: "Roasted Pork Udon", image: "新菜品图/汤面/Udon/Roasted Pork Udon cutout.png", price: "$16.50" },
  { category: "Udon", name: "Tempura Udon", image: "新菜品图/汤面/Udon/N4 Tempura Udon remade.png", price: "$16.50" },
  { category: "Deluxe Bento", name: "Salmon Sashimi Deluxe Bento", image: "新菜品图/豪华便当/B10 Salmon Sashimi Deluxe Bento salad.png", price: "$19.80" },
  { category: "Deluxe Bento", name: "Karaage Chicken Deluxe Bento", image: "新菜品图/豪华便当/B6 Karaage Chicken Deluxe Bento.png", price: "$17.50" },
  { category: "Deluxe Bento", name: "Yaki-Soba Deluxe Bento", image: "新菜品图/豪华便当/B12 Yaki-Soba Deluxe Bento salad.png", price: "$19.80" },
  { category: "Deluxe Bento", name: "Teriyaki Chicken Deluxe Bento", image: "新菜品图/豪华便当/B7 Teriyaki chicken Deluxe Bento .png", price: "$17.50" },
  { category: "Deluxe Bento", name: "Veg Tempura Deluxe Bento", image: "新菜品图/豪华便当/B11 Veg Tempura Deluxe Bento.png", price: "$17.50" },
  { category: "Deluxe Bento", name: "Yakiniku Beef Deluxe Bento", image: "新菜品图/豪华便当/B9 Yakiniku Beef  Deluxe Bento.png", price: "$17.50" },
  { category: "Deluxe Bento", name: "Chicken Katsu Deluxe Bento", image: "新菜品图/豪华便当/B8 Chicken Katsu Deluxe Bento.png", price: "$17.50" },
  { category: "Fried Rice & Noodles", name: "Japanese Stir Fried Udon", image: "新菜品图/炒饭炒面/Japanese Stir Fried Udon.png", price: "$14.80", variants: [{ label: "Veg", price: "$14.80" }, { label: "Chicken", price: "$16.50" }, { label: "Beef", price: "$16.50" }, { label: "Seafood", price: "$17.50" }] },
  { category: "Fried Rice & Noodles", name: "Japanese Stir Fried Rice", image: "新菜品图/炒饭炒面/Japanese Stir Fried Rice.png", price: "$13.90", variants: [{ label: "Veg", price: "$13.90" }, { label: "Chicken", price: "$15.80" }, { label: "Beef", price: "$15.80" }, { label: "Seafood", price: "$16.80" }] },
  { category: "Fried Rice & Noodles", name: "Japanese Yaki-Soba Noodles", image: "新菜品图/炒饭炒面/Japanese Yaki-Soba Noodles.png", price: "$13.90", variants: [{ label: "Veg", price: "$13.90" }, { label: "Chicken", price: "$15.80" }, { label: "Beef", price: "$15.80" }, { label: "Seafood", price: "$16.80" }] },
  { category: "Donburi & Curry", name: "Karaage Chicken Don", image: "新菜品图/咖喱盖饭/generated/Karaage Chicken Don.png?v=tiny-pickle-1", price: "$14.80", variants: [{ label: "Don", price: "$14.80", image: "新菜品图/咖喱盖饭/generated/Karaage Chicken Don.png?v=tiny-pickle-1" }, { label: "Curry", price: "$16.50", image: "新菜品图/咖喱盖饭/generated/Karaage Chicken Curry.png?v=tiny-pickle-1" }] },
  { category: "Donburi & Curry", name: "Teriyaki Chicken Don", image: "新菜品图/咖喱盖饭/generated/Teriyaki Chicken Don.png?v=tiny-pickle-1", price: "$14.80", variants: [{ label: "Don", price: "$14.80", image: "新菜品图/咖喱盖饭/generated/Teriyaki Chicken Don.png?v=tiny-pickle-1" }, { label: "Curry", price: "$16.50", image: "新菜品图/咖喱盖饭/generated/Teriyaki Chicken Curry.png?v=tiny-pickle-1" }] },
  { category: "Donburi & Curry", name: "Chicken Katsu Don", image: "新菜品图/咖喱盖饭/generated/Chicken Katsu Don.png?v=tiny-pickle-1", price: "$14.80", variants: [{ label: "Don", price: "$14.80", image: "新菜品图/咖喱盖饭/generated/Chicken Katsu Don.png?v=tiny-pickle-1" }, { label: "Curry", price: "$16.50", image: "新菜品图/咖喱盖饭/generated/Chicken Katsu Curry.png?v=tiny-pickle-1" }] },
  { category: "Donburi & Curry", name: "Gyu Beef Don", image: "新菜品图/咖喱盖饭/generated/Gyu Beef Don.png?v=tiny-pickle-1", price: "$14.80", variants: [{ label: "Don", price: "$14.80", image: "新菜品图/咖喱盖饭/generated/Gyu Beef Don.png?v=tiny-pickle-1" }, { label: "Curry", price: "$16.50", image: "新菜品图/咖喱盖饭/generated/Gyu Beef Curry.png?v=tiny-pickle-1" }] },
  { category: "Donburi & Curry", name: "Yakiniku Beef Don", image: "新菜品图/咖喱盖饭/generated/Yakiniku Beef Don.png?v=tiny-pickle-1", price: "$14.80", variants: [{ label: "Don", price: "$14.80", image: "新菜品图/咖喱盖饭/generated/Yakiniku Beef Don.png?v=tiny-pickle-1" }, { label: "Curry", price: "$16.50", image: "新菜品图/咖喱盖饭/generated/Yakiniku Beef Curry.png?v=tiny-pickle-1" }] },
  { category: "Donburi & Curry", name: "Chicken Oyakodon", image: "新菜品图/咖喱盖饭/R6 Chicken Oyakodon.png", price: "$15.80" },
  { category: "Donburi & Curry", name: "Kabayaki Eel Don", image: "新菜品图/咖喱盖饭/R7 Kabayaki Eel Don.png", price: "$18.80" },
  { category: "Donburi & Curry", name: "Teriyaki Salmon Don", image: "新菜品图/咖喱盖饭/teriyaki salmon don.JPG", price: "$17.50" },
  { category: "Donburi & Curry", name: "Vegetable Tofu Curry", image: "新菜品图/咖喱盖饭/R9 Vegetable Tofu Curry.png", price: "$16.50" },
  { category: "Donburi & Curry", name: "Sweet Sour Chicken Don", image: "新菜品图/咖喱盖饭/R11 Sweet Sour Chicken Don.png", price: "$15.50" },
  { category: "Donburi & Curry", name: "Tofu Yasai Don", image: "新菜品图/咖喱盖饭/tofu yasai don.JPG", price: "$15.50" },
  { category: "Sushi", name: "Sushi Party Platter A", image: "新菜品图/寿司拼盘/1. Sushi Party Platter.jpg", price: "$40.00", variants: [{ label: "Small", price: "$40.00" }, { label: "Large", price: "$50.00" }] },
  { category: "Sushi", name: "Sushi Party Platter B", image: "新菜品图/寿司拼盘/2. Sushi Party Platter.jpg", price: "$40.00", variants: [{ label: "Small", price: "$40.00" }, { label: "Large", price: "$50.00" }] },
  { category: "Sushi", name: "Crispy chicken roll", image: "新菜品图/sushi/Crispy chicken roll.png", price: "$4.50" },
  { category: "Sushi", name: "Chicken katsu roll", image: "新菜品图/sushi/Chicken katsu roll.png", price: "$4.50" },
  { category: "Sushi", name: "Teriyaki chicken roll", image: "新菜品图/sushi/Teriyaki chicken roll.png", price: "$4.50" },
  { category: "Sushi", name: "Spicy chicken roll", image: "新菜品图/sushi/Spicy chicken roll.png", price: "$4.50" },
  { category: "Sushi", name: "Crumbed prawn roll", image: "新菜品图/sushi/Crumbed prawn roll.png", price: "$4.50" },
  { category: "Sushi", name: "Spicy prawn roll", image: "新菜品图/sushi/Spicy prawn roll.png", price: "$4.50" },
  { category: "Sushi", name: "Cooked prawn roll", image: "新菜品图/sushi/Cooked prawn roll.png", price: "$4.50" },
  { category: "Sushi", name: "Cooked tuna roll", image: "新菜品图/sushi/Cooked tuna roll.png", price: "$4.50" },
  { category: "Sushi", name: "California roll", image: "新菜品图/sushi/California roll.png", price: "$4.50" },
  { category: "Sushi", name: "Salmon avocado roll", image: "新菜品图/sushi/Salmon avocado roll.png", price: "$4.50" },
  { category: "Sushi", name: "Teriyaki salmon roll", image: "新菜品图/sushi/Teriyaki salmon roll.png", price: "$4.50" },
  { category: "Sushi", name: "Spicy salmon roll", image: "新菜品图/sushi/Spicy salmon roll.png", price: "$4.50" },
  { category: "Sushi", name: "Avocado roll", image: "新菜品图/sushi/Avocado roll.png", price: "$4.50" },
  { category: "Sushi", name: "Vegetable roll", image: "新菜品图/sushi/Vegetable roll.png", price: "$4.50" },
  { category: "Sides", name: "Crumbed Prawn", image: "新菜品图/小菜/S5 Crumbed Prawn.png", price: "$8.00" },
  { category: "Sides", name: "Vegetable Spring Roll", image: "新菜品图/小菜/S2 Vegetable spring Roll.png", price: "$5.00" },
  { category: "Sides", name: "Japanese Croquette", image: "新菜品图/小菜/S11 Japanese croquette.png", price: "$6.00" },
  { category: "Sides", name: "Edamame", image: "新菜品图/小菜/S14 Edmame.png", price: "$5.50" },
  { category: "Sides", name: "Salmon Sashimi", image: "新菜品图/小菜/S6 Salmon Sashimi.png", price: "$9.80" },
  { category: "Sides", name: "Teriyaki Tofu", image: "新菜品图/小菜/S15 Teriyaki Tofu.png", price: "$6.00" },
  { category: "Sides", name: "Karaage Chicken", image: "新菜品图/小菜/S1 Karaage Chicken.png", price: "$7.00" },
  { category: "Sides", name: "Takoyaki", image: "新菜品图/小菜/S3 Takoyaki.png", price: "$7.00" },
  { category: "Sides", name: "Veg Tempura", image: "新菜品图/小菜/S10 Veg Tempura menu.png", price: "$6.00" },
  { category: "Sides", name: "Agedashi Tofu", image: "新菜品图/小菜/S8 Agedashi Tofu.png", price: "$6.00" },
  { category: "Sides", name: "Seaweed Salad", image: "新菜品图/小菜/S13 Seaweed Salad.png", price: "$4.50" },
  { category: "Drinks", name: "600ml Bottled Soft Drink", image: "新菜品图/Drinks/Coke Classic 600ml Bottle.png", price: "$5.50", variants: [{ label: "Classic Coke", price: "$5.50", image: "新菜品图/Drinks/Coke Classic 600ml Bottle.png" }, { label: "Sprite", price: "$5.50", image: "新菜品图/Drinks/Sprite 600ml Bottle.png" }, { label: "Fanta Orange", price: "$5.50", image: "新菜品图/Drinks/Fanta Orange 600ml Bottle.png" }, { label: "Coke No Sugar", price: "$5.50", image: "新菜品图/Drinks/Coke No Sugar 600ml Bottle.png" }, { label: "Vanilla Coke", price: "$5.50", image: "新菜品图/Drinks/Vanilla Coke 600ml Bottle.png" }, { label: "Vanilla Coke No Sugar", price: "$5.50", image: "新菜品图/Drinks/Vanilla Coke No Sugar 600ml Bottle.png" }] },
  { category: "Drinks", name: "375ml Canned Soft Drink", image: "新菜品图/Drinks/Coke Classic 375ml Can.png", price: "$3.50", variants: [{ label: "Classic Coke", price: "$3.50", image: "新菜品图/Drinks/Coke Classic 375ml Can.png" }, { label: "Sprite", price: "$3.50", image: "新菜品图/Drinks/Sprite 375ml Can.png" }, { label: "Coke No Sugar", price: "$3.50", image: "新菜品图/Drinks/Coke No Sugar 375ml Can.png" }, { label: "Fanta Orange", price: "$3.50", image: "新菜品图/Drinks/Fanta Orange 375ml Can.png" }] },
  { category: "Drinks", name: "Pump Water 750ml", image: "新菜品图/Drinks/Pump Water 750ml.png", price: "$5.50" },
  { category: "Drinks", name: "Mount Franklin Still Water", image: "新菜品图/Drinks/Mount Franklin Still Water.png", price: "$3.50" },
  { category: "Drinks", name: "Mount Franklin Sparkling Water", image: "新菜品图/Drinks/Mount Franklin Sparkling Water.png", price: "$4.50" },
  { category: "Drinks", name: "Keri Juice 375ml", image: "新菜品图/Drinks/Keri Apple Juice.png", price: "$5.50", variants: [{ label: "Apple", price: "$5.50", image: "新菜品图/Drinks/Keri Apple Juice.png" }, { label: "Orange", price: "$5.50", image: "新菜品图/Drinks/Keri Orange Juice.png" }] },
  { category: "Drinks", name: "Fuze Iced Tea", image: "新菜品图/Drinks/Fuze Peach Iced Tea.png", price: "$5.50", variants: [{ label: "Peach", price: "$5.50", image: "新菜品图/Drinks/Fuze Peach Iced Tea.png" }, { label: "Lemon", price: "$5.50", image: "新菜品图/Drinks/Fuze Lemon Iced Tea.png" }, { label: "Mango", price: "$5.50", image: "新菜品图/Drinks/Fuze Mango Iced Tea.png" }] },
  { category: "Others", name: "Miso Soup", image: "新菜品图/Others/Miso Soup.png", price: "$3.50" },
  { category: "Others", name: "Japanese Green Tea", image: "新菜品图/Others/Japanese Green Tea.png", price: "$4.50" },
  { category: "Others", name: "Steam Rice", image: "新菜品图/Others/Steam Rice.png", price: "$3.50" },
  { category: "Gyoza", name: "Gyoza 5pc", image: "新菜品图/饺子/Gyoza 5pc plate.png", price: "$6.50", variants: [{ label: "Chicken", price: "$6.50" }, { label: "Pork", price: "$6.50" }] },
  { category: "Gyoza", name: "Gyoza 10pc", image: "新菜品图/饺子/Gyoza 10pc plate.png", price: "$12.00", variants: [{ label: "Chicken", price: "$12.00" }, { label: "Pork", price: "$12.00" }] },
  { category: "Classic Bento", name: "Chicken Katsu Bento", image: "新菜品图/经典便当/B3 Chicken Katsu Bento.png", price: "$15.50" },
  { category: "Classic Bento", name: "Yakiniku Beef Bento", image: "新菜品图/经典便当/B5 Yakiniku Beef Bento.png", price: "$15.50" },
  { category: "Classic Bento", name: "Shogayaki Beef Bento", image: "新菜品图/经典便当/B5 Yakiniku Beef Bento.png", price: "$15.50" },
  { category: "Classic Bento", name: "Karaage Chicken Classic Bento", image: "新菜品图/经典便当/B1 Karaga Chicken Classical Bento.png", price: "$15.50" },
  { category: "Classic Bento", name: "Teriyaki Beef Bento", image: "新菜品图/经典便当/B4 Teriyaki Beef Bento.png", price: "$15.50" },
  { category: "Classic Bento", name: "Teriyaki Chicken Bento", image: "新菜品图/经典便当/B2 Teriyaki Chicken Bento.png", price: "$15.50" }
].map((item) => ({ ...item, price: item.price || "$14.90" }));
