const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const base = 'http://127.0.0.1:4182';
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => { errors.push(error.message); console.error('PAGE ERROR:', error.message); });
    await fs.mkdir('output/playwright', { recursive: true });
    await page.goto(`${base}/menu.html?category=Donburi%20%26%20Curry`);
    await page.waitForFunction(() => { const img = document.querySelector('.menu-card img'); return img?.complete && img.naturalWidth > 0; });
    console.log((await page.locator('body').ariaSnapshot()).slice(0, 5000));
    await page.screenshot({ path: 'output/playwright/menu-mobile.png' });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    const dish = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Karaage Chicken Don', exact: true }) });
    const original = await dish.locator('img').getAttribute('src');
    await dish.getByText('Curry $16.50', { exact: true }).click();
    assert.notEqual(await dish.locator('img').getAttribute('src'), original);
    await dish.getByRole('button', { name: 'Add', exact: true }).click();
    assert.equal(await page.locator('#mobileCartTotal').textContent(), '$16.50');
    await page.getByRole('searchbox').fill('dumplings');
    assert.equal(await page.locator('.menu-card').count(), 2);
    await page.getByRole('searchbox').fill('nothingmatched123');
    assert.ok(await page.getByRole('button', { name: 'See all dishes' }).isVisible());
    await page.getByRole('button', { name: 'See all dishes' }).click();
    await page.locator('#mobileCart').click();
    await page.locator('#orderMail').click();
    await page.waitForURL('**/checkout.html');
    assert.doesNotMatch(await page.locator('.payment-note').textContent(), /restaurant confirmation/i);
    console.log((await page.locator('body').ariaSnapshot()).slice(0, 5000));
    await page.getByRole('button', { name: 'Add one Karaage Chicken Don (Curry)' }).click();
    assert.equal(await page.locator('#submitTotal').textContent(), '$33.00');
    await page.screenshot({ path: 'output/playwright/checkout-mobile.png' });
    await page.getByLabel('Name', { exact: true }).fill('Test guest');
    await page.getByLabel('Phone', { exact: true }).fill('0400000000');
    await page.getByLabel('Email', { exact: true }).fill('test@example.com');
    let date = new Date(Date.now() + 3 * 86400000);
    while (date.getUTCDay() === 6) date = new Date(+date + 86400000);
    await page.getByLabel('Pickup date', { exact: true }).fill(date.toISOString().slice(0, 10));
    await page.getByRole('combobox', { name: 'Pickup time', exact: true }).selectOption('13:00');
    await page.getByText('Yes, please', { exact: true }).click();
    await page.getByLabel('Number of cutlery sets').fill('2');
    await page.getByRole('button', { name: 'Place order' }).click();
    await page.waitForURL('**/success.html?type=order');
    assert.equal(await page.locator('#successTitle').textContent(), 'Thank you for your order');
    assert.ok((await page.locator('#successSummary').textContent()).includes('$33.00'));
    assert.match(await page.locator('#successSummary').textContent(), /Order received/);
    assert.doesNotMatch(await page.locator('main').textContent(), /awaiting|restaurant confirmation/i);
    await page.screenshot({ path: 'output/playwright/success-mobile.png' });
    const emptyPage = await context.newPage();
    await emptyPage.goto(`${base}/success.html?type=order`);
    assert.equal(await emptyPage.locator('#successTitle').textContent(), 'We cannot verify a request here');
    await page.goto(`${base}/index.html`);
    assert.equal(await page.locator('[data-cart-count]').textContent(), '0');
    assert.equal(await page.locator('[data-special-hours]').isVisible(), false);
    await page.screenshot({ path: 'output/playwright/home-mobile.png' });
    const reservation = page.locator('#reservationForm');
    await reservation.getByLabel('Name', { exact: true }).fill('Test guest');
    await reservation.getByLabel('Phone', { exact: true }).fill('0400000000');
    await reservation.getByLabel('Email', { exact: true }).fill('test@example.com');
    let saturday = new Date(Date.now() + 7 * 86400000);
    while (saturday.getUTCDay() !== 6) saturday = new Date(+saturday + 86400000);
    await reservation.getByLabel('Date', { exact: true }).fill(saturday.toISOString().slice(0, 10));
    assert.ok(await reservation.getByRole('combobox', { name: 'Reservation time' }).isDisabled());
    await reservation.getByLabel('Date', { exact: true }).fill(date.toISOString().slice(0, 10));
    await reservation.getByRole('combobox', { name: 'Reservation time' }).selectOption('13:00');
    await reservation.screenshot({ path: 'output/playwright/reservation-mobile.png' });
    await reservation.getByRole('button', { name: 'Request a table' }).click();
    await page.waitForURL('**/success.html?type=reservation');
    assert.equal(await page.locator('#successTitle').textContent(), 'Thank you for your reservation');
    assert.ok((await page.locator('#successSummary').textContent()).includes('AP-R-'));
    for (const width of [360, 768, 1280, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      await page.goto(`${base}/menu.html?category=Gyoza`);
      await page.waitForFunction(() => [...document.querySelectorAll('.menu-card img')].slice(0, 2).every(img => img.complete && img.naturalWidth > 0));
      await page.locator('.menu-card img').evaluateAll(images => Promise.all(images.map(img => img.decode())));
      console.log('Image boxes', width, await page.locator('.menu-card img').evaluateAll(images => images.map(img => ({src: img.currentSrc, width: img.clientWidth, height: img.clientHeight, opacity: getComputedStyle(img).opacity, visibility: getComputedStyle(img).visibility}))));
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `overflow at ${width}`);
      await page.screenshot({ path: `output/playwright/menu-${width}.png` });
    }
    await page.getByRole('button', { name: 'View Gyoza 5pc' }).click();
    assert.ok(await page.getByRole('dialog').isVisible());
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('dialog').isVisible(), false);
    assert.deepEqual(errors, []);
    console.log('PASS: mobile cart, variant images, search, checkout quantities, dry-run submission, success guard, responsive overflow.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
